### ISSUE TITLE
GUI Widgets

### ISSUE THREAD

**Issue by karai17** [excessive/DOMinatrix#12]
The general idea here is to be able to define a sort of GUI "class" that can be used extensively. A great example would be building a generic name plate widget complete with avatar, name, health bar, etc. The widget can be used for the player, party members, targeted enemy, etc.

This feature is an absolute must.

**Comment by karai17** [comment]
When writing markup, widgets will define what to do with subtables.

``` lua
{ "widget", "window_frame",
    { "textbox", "Player_Name" },
    { "textbox", "Player_Class" },
    -- ...
}
```

In the above example, we have a generic "window_frame" widget and we want to add several textboxes to it. In this widget, there is a definition to say "append all subtables to my frame element". This will allow extendable widgets, widgets within widgets, etc.

**Comment by adrix89** [comment]
Instead of widgets why not have more custom classes/types? Isn't that what they are anyway? why widget?

**Comment by karai17** [comment]
Users will be able to extend elements to be able to create their own. The
point of widgets is to create a generic group of objects with predefined
styles and scripts that can be reused. A simple example of this would be
name plates in an mmo. You, your target, your party, there could be several
name plates that should be able to be included without needing to be
redefined every time.
