### ISSUE TITLE
on_mouse_over

### ISSUE THREAD

**Issue by SiENcE** [excessive/DOMinatrix#16]
If you wanna show tooltips this is important.

Only using enter and leave does not work in love2d, because they are only called when window is active.

**Comment by karai17** [comment]
Can you elaborate more? Enter/leave are not love callbacks, they are custom
functions that will constantly poll the element list using the mouse
position.

**Comment by SiENcE** [comment]
Think of window mode, if you go with mouse into an area and show a tooltip, but than switch of of the love2d window, than back, but mousecursor is now on a different position, you normally want to hide the tooltip now...but you can't because  enter and leave it not called.

**Comment by karai17** [comment]
That's a fair point. I'll be sure to add a basic hover callback, too.
